release-type: node
package-name: html2img
bump-minor-pre-major: true
bump-patch-for-minor-pre-major: true
changelog-types:
  - type: feat
    section: Features
    hidden: false
  - type: fix
    section: Bug Fixes
    hidden: false
  - type: docs
    section: Documentation
    hidden: false
  - type: chore
    section: Maintenance
    hidden: false
  - type: refactor
    section: Code Refactoring
    hidden: false
  - type: test
    section: Tests
    hidden: false
  - type: build
    section: Build System
    hidden: false
  - type: ci
    section: Continuous Integration
    hidden: false
  - type: perf
    section: Performance Improvements
    hidden: false
  - type: style
    section: Code Style
    hidden: false
  - type: revert
    section: Reverts
    hidden: false
include-v-in-tag: true
release-as: 1.0.0 