name: release-please
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: html2img
          token: ${{ secrets.GITHUB_TOKEN }}
          command: manifest
          changelog-types: |
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"docs","section":"Documentation","hidden":false},
              {"type":"chore","section":"Maintenance","hidden":false},
              {"type":"refactor","section":"Code Refactoring","hidden":false},
              {"type":"test","section":"Tests","hidden":false},
              {"type":"build","section":"Build System","hidden":false},
              {"type":"ci","section":"Continuous Integration","hidden":false},
              {"type":"perf","section":"Performance Improvements","hidden":false},
              {"type":"style","section":"Code Style","hidden":false},
              {"type":"revert","section":"Reverts","hidden":false}
            ] 